### ISSUE TITLE
uPy-specific top-level functions like `const`

### ISSUE THREAD

**Issue by jdtsmith** [Josverl/micropython-stubs#119]
Do stubs have a way to feed in top level functions like `const`? I see that `const` is defined in `micropython.py`, but this does not allow Jedi etc. to infer that a top level call to `const` is valid (aside from doing `from micropython import const`).

**Comment by Josverl** [comment]
I never realized that const could be used even without importing it , even though the documentation says that it [**should** be imported.](https://docs.micropython.org/en/latest/library/micropython.html?highlight=const#micropython.const)

In a quick test It indeed works , but not for all functions in the micropython module and only in assignments 
``` python 
>>> print(const(42))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'const' isn't defined
>>> answer = const(42)
>>> print(answer)
42
>>>
``` 
so I'm not sure for which functions you would want to make this work.

apart from that, I think  Chris Wood seems to have found a way to 'automagically' load definitions in PyLance.
I think he is using a side effect of PyLance loading `stdlib` to also load a bunch of other modules.

See : https://github.com/cpwood/Pico-Stub/tree/main/dist/pylance and the pico-go VSCode add-in.
Note that this requires  a very specific configuration of the various path settings,
and I do not fully understand this , so cannot tell if this would work to solve your ask as well.

**Comment by jdtsmith** [comment]
I don't think it means you should import, just that if you want, you can import, and then define `const` away and run the same code in CPython without error (by providing a fake micropython no-op library).   But it's not too much of a hardship to import.
