### ISSUE TITLE
Update pymakr.conf with py_ignore all-stubs

### ISSUE THREAD

**Issue by Simpler1** [Josverl/micropython-stubs#62]
It should be added to the documentation to update pymakr.conf and add "all-stubs" to the "py_ignore" section.

**Comment by Josverl** [comment]
Agree that makes total sense.

**Comment by Josverl** [comment]
Added to RTD 
https://micropython-stubs.readthedocs.io/en/moduledocs/02_using.html#pymakr-update-pymakr-conf
