### ISSUE TITLE
Wrong link behind 'Create a symbolic link' in your README.md

### ISSUE THREAD

**Issue by hcet14** [Josverl/micropython-stubs#83]
I have no clue how to reate a symbolic link ;)

**Comment by Josverl** [comment]
The correct link is : https://github.com/Josverl/micropython-stubs#create-a-symbolic-link
( or just search in the readme.txt)

**Comment by Josverl** [comment]
Moved the documentation to RTD :
build process now includes link checkers , so I hope this will avoid errors like you ean into.
https://micropython-stubs.readthedocs.io/en/moduledocs/04_symlink.html
